name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install gexiv2 dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libgexiv2-dev
          
      - name: Install GTK, Cairo, and Pango dependencies
        run: sudo apt-get update && sudo apt-get install -y libgtk-3-dev libpango1.0-dev libcairo2-dev

      - name: Set PKG_CONFIG_PATH (optional, usually handled automatically)
        run: echo "PKG_CONFIG_PATH=/usr/lib/x86_64-linux-gnu/pkgconfig" >> $GITHUB_ENV
        
      - name: Build
        run: cargo build --verbose

      - name: Run tests
        run: cargo test --verbose
